### ISSUE TITLE
Pushing to WPEngine

### ISSUE THREAD

**Issue by cgrymala** [highedweb/membership-site#10]
I'm running into some access issues when trying to push/pull with WPEngine. I'm working on trying to figure out how to get them fixed, but, if someone else gets a chance before I straighten them out, can you please go ahead and push the latest version (I committed an update to Akismet and an update to iThemes Security (better-wp-security)). Thanks.

**Comment by woodwardjd** [comment]
Done!  I pushed the latest that's on github
[ cfbba5c5b80a67ced70e6b6075d09ff8cc0e6111 ] to wpengine prod
[ git@git.wpengine.com:production/hewmembership.git ]

On Mon, Jun 8, 2015 at 9:03 AM, Curtiss Grymala <notifications@github.com>
wrote:

> I'm running into some access issues when trying to push/pull with
> WPEngine. I'm working on trying to figure out how to get them fixed, but,
> if someone else gets a chance before I straighten them out, can you please
> go ahead and push the latest version (I committed an update to Akismet and
> an update to iThemes Security (better-wp-security)). Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/highedweb/membership-site/issues/10>.
>



-- 
Jason Woodward
http://www.woodwardjd.com
@woodwardjd

**Comment by cgrymala** [comment]
Awesome. Thanks, Jason.
